# Generated by Django 3.1.2 on 2020-10-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo2',
        ),
    ]
